# Generated by Django 6.0.3 on 2026-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Markdown-supported problem statement.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='example_input',
            field=models.TextField(blank=True, help_text='Shown to student as sample input.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='example_output',
            field=models.TextField(blank=True, help_text='Shown to student as expected output.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='memory_limit',
            field=models.CharField(default='64m', help_text='Memory limit e.g. 64m.', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.PositiveIntegerField(default=5, help_text='Execution time limit in seconds.'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(help_text='Expected stdout (stripped for comparison).'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, help_text="stdin fed to the student's program."),
        ),
    ]
