# Generated by Django 6.0.3 on 2026-03-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_description_alter_task_example_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='coin_reward',
            field=models.PositiveIntegerField(default=0, help_text='Coins awarded on first correct solve. 0 = no reward.'),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', help_text='Used only for global challenges.', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='scope',
            field=models.CharField(choices=[('session', 'Session only'), ('global', 'Global challenge')], default='session', help_text='Session = only used inside a class session. Global = open to everyone.', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Only published global challenges are visible to students.', max_length=12),
        ),
    ]
