# Generated by Django 6.0.3 on 2026-03-19 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_language'),
        ('tasks', '0003_task_coin_reward_task_difficulty_task_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_awarded', models.PositiveIntegerField(default=0)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solve_record', to='submissions.submission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_challenges', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solved_at'],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
