# Generated by Django 6.0.3 on 2026-03-22 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-globe', help_text='Bootstrap icon class, e.g. bi-code-slash', max_length=60, verbose_name='icon')),
                ('color', models.CharField(default='#0d9488', help_text='Hex color for the category accent', max_length=7, verbose_name='color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, help_text='Shown on the card. Falls back to description if empty.', max_length=160, verbose_name='short description')),
                ('color', models.CharField(default='#0d9488', help_text='Hex color for the card logo background', max_length=7, verbose_name='accent color')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='resources.category', verbose_name='category')),
                ('tags', models.ManyToManyField(blank=True, related_name='websites', to='resources.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'ordering': ['order', 'name'],
            },
        ),
    ]
