# Generated by Django 6.0.3 on 2026-03-22 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('admin_note', models.TextField(blank=True, help_text='Optional note shown to the user', verbose_name='admin note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.category', verbose_name='category')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='suggested by')),
            ],
            options={
                'verbose_name': 'Website Suggestion',
                'verbose_name_plural': 'Website Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
