# Generated by Django 6.0.3 on 2026-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_websitesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesuggestion',
            name='suggested_category',
            field=models.CharField(blank=True, help_text='If your category is not in the list above, type it here', max_length=100, verbose_name='suggested category'),
        ),
    ]
