# Generated by Django 6.0.3 on 2026-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_websitesuggestion_suggested_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='websitesuggestion',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
