# Generated by Django 6.0.3 on 2026-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_website_url_alter_websitesuggestion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='websitesuggestion',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
