# Generated by Django 6.0.3 on 2026-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_groupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student')], default='', max_length=10),
        ),
    ]
