# Generated by Django 6.0.3 on 2026-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_session_activated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Exact moment teacher clicked Start — used for countdown timer.', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Session duration in minutes. 0 = no time limit.'),
        ),
    ]
