# Generated by Django 6.0.3 on 2026-04-06 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='test_pack',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testpack',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='testpack',
            name='group',
        ),
        migrations.RemoveField(
            model_name='testpack',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='testpack',
            name='coin_reward',
            field=models.PositiveIntegerField(default=0, help_text="Faqat Global test uchun. Max 5. Faqat 100% to'g'ri bo'lsa beriladi."),
        ),
        migrations.AlterField(
            model_name='testpack',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Faqat Global test uchun. 0 = vaqt cheklovsiz.'),
        ),
        migrations.AlterField(
            model_name='testpack',
            name='mode',
            field=models.CharField(choices=[('session', 'Session uchun'), ('global', 'Global (har doim mavjud)')], default='session', max_length=10),
        ),
        migrations.CreateModel(
            name='GlobalTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], default='ongoing', max_length=10)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('coins_awarded', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_test_attempts', to=settings.AUTH_USER_MODEL)),
                ('test_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_attempts', to='tests_app.testpack')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_app.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_app.globaltestattempt')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
    ]
